name: nano-shutter
services:
  api:
    build: .
    restart: unless-stopped
    environment:
      PORT: 5000
    command: ["./nano-shutter"]
    labels:
      caddy: "${SERVICE_DOMAIN_NAME}"
      caddy.reverse_proxy: "{{ upstreams 5000 }}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    restart: always
    volumes:
      - ${DATA_DIR:-./data}/caddy:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - "443:443"
      - "443:443/udp"
    labels:
      caddy.email: "devops@brainbot.com"